defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      permalink: "/:title.html"
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
      permalink: "/:category/:title/"
  - scope:
      path: ""
      type: tag
    values:
      layout: "tag"
      permalink: "/tags/:tag/:title/"
exclude:
  ["andk-jekyll.sublime-project","andk-jekyll.sublime-workspace", "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
collections:
  category:
    output: true
title: No More • self-care for you and your apps
url: https://nomore.software
description: No More helps make your apps weirder, nicer, and less addictive.
google_analytics: "UA-39284830-3"
plugins:
  - jekyll-feed
excerpt_separator: <!--more-->
